# Generated by Django 3.0.3 on 2020-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200229_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
